name: shohoj_hisab
description: "সহজ হিসাব - দৈনিক ও মাসিক গড় ক্যালকুলেটর"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"
  adaptive_icon_background: "#06130F"
  adaptive_icon_foreground: "icon.png"

flutter:
  uses-material-design: true
