name: Flutter Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Android project
        run: |
          rm -rf android
          flutter create --platforms=android .

      - name: Add Internet Permission
        run: |
          if ! grep -q "android.permission.INTERNET" android/app/src/main/AndroidManifest.xml; then
            sed -i '/<manifest/a\    <uses-permission android:name="android.permission.INTERNET"/>' \
              android/app/src/main/AndroidManifest.xml
          fi

      - name: Analyze
        run: flutter analyze lib --no-fatal-infos

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: shohoj-hisab-apk
          path: build/app/outputs/flutter-apk/app-release.apk
